- name: Node.js | Install stack dependencies
  npm: name={{ item }} global=yes
  sudo: yes
  with_items:
    - bower
    - grunt-cli
    - mocha
    - meanio

- name: Initialize stack.
  sudo: yes
  sudo_user: "{{ user_name }}"
  command: mean init tokamak chdir=/home/vagrant/

- name: Install mean.io packages.
  sudo: yes
  sudo_user: "{{ user_name }}"
  npm: path={{ mean_directory }} state=present

- name: Install Tokamak mean.io package.
  sudo: yes
  sudo_user: "{{ user_name }}"
  copy: src=../packages dest={{ mean_directory }}/

- name: Install Tokamak mean.io package dependencies.
  sudo: yes
  sudo_user: "{{ user_name }}"
  npm: path={{ tokamak_package_directory }} state=present

- name: Install supervisord config file
  template: src=supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf owner=root mode=0600

- name: Install mean.io supervisor config file
  template: src=supervisord_mean.conf.j2 dest=/etc/supervisor/conf.d/mean.conf
  sudo: yes

- name: reload supervisord
  command: supervisorctl reload
  sudo: yes

- name: Make sure mean.io stack is present.
  sudo: yes
  action: supervisorctl name={{ project_name }} state=present
