- name: set locale to {{ locale }}
  action: command /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
  sudo: yes

- name: Install required system packages.
  action: apt pkg={{ item }} state=installed update-cache=yes state=installed
  sudo: yes
  with_items:
    - build-essential
    - git
    - nodejs
    - nodejs-dev
    - npm
    - mongodb
    - supervisor

- name: Create a nodejs link to make npm builds happy.
  sudo: yes
  action: file state=link src=/usr/bin/nodejs dest=/usr/bin/node

# For deployments only.
- name: Create user.
  sudo: yes
  action: user home=/home/{{ user_name }} name={{ user_name }} state=present
  when: not vagrant

- name: Create the project directory.
  sudo: yes
  action: file state=directory path={{ project_directory }}
  when: not vagrant
